### ISSUE TITLE
Language extensions 

### ISSUE THREAD

**Issue by ghost** [Cauterization/EchoBot#7]
В модулях часто встречаются одни и те же прагмы, хорошо бы было их вынести в `package.yaml`

**Comment by Cauterization** [comment]
> В модулях часто встречаются одни и те же прагмы, хорошо бы было их вынести в `package.yaml`

Без них ormolu не работает.

**Comment by ghost** [comment]
Тут есть несколько вариантов:
1. Если используешь HLS и возможности расширение текстового редактора позволяет дергать форматтер через хлс, то оно автоматически должно подхватывать все расширения. 
2.  Вручную указывать расширения в опциях ormolu. Например: ` --ghc-opt -XImportQualifiedPost `
3. Брать их из `.cabal` файла( для этого  нужно будет перегенерить `.cabal` через stack или напрямую через hpack) при помощи опци `-e` или `--cabal-default-extensions`
